name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # 1. Repository'yi checkout et
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Python'u kur
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      # 3. Gereksinimleri yükle
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      # 4. Testleri çalıştır
      #- name: Run tests
       # run: |
          #python -m pytest tests/