name: Publish Package

on:
  push:
    tags:
      - 'v*'  # v1.0.0 gibi etiketlerde tetiklenir

# İş akışı için gerekli izinler
permissions:
  contents: write  # Paketleri GitHub Packages'e yüklemek için
  packages: write  # GitHub Packages'e erişim için

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel

      - name: Build package
        run: |
          python setup.py sdist bdist_wheel

      - name: Publish to GitHub Packages
        uses: pypa/gh-action-pypi-publish@release/v1  # Sabit bir SHA hash kullanın
        with:
          user: __token__
          password: ${{ secrets.GITHUB_TOKEN }}
          repository-url: https://github.com/emredeveloper/RAG_Deepseek  # Kullanıcı adınızı ekleyin